services:
  - type: web
    name: google-maps-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_flask:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18
